# Generated by Django 3.2.20 on 2025-08-29 18:33

import File_Sharing_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Sharing_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=File_Sharing_App.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
